///************************************************
/// Generated by: tuandm
/// Date: 19/10/2015 10:56:59
/// Goal: Create User Service Class for DS_HO_SO_THI_SINH
///************************************************
/// <summary>
/// Create User Service Class for DS_HO_SO_THI_SINH
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DS_HO_SO_THI_SINH : US_Object
	{
		private const string c_TableName = "DS_HO_SO_THI_SINH";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strMA_THI_SINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "MA_THI_SINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["MA_THI_SINH"] = value;
			}
		}

		public bool IsMA_THI_SINHNull() 
		{
			return pm_objDR.IsNull("MA_THI_SINH");
		}

		public void SetMA_THI_SINHNull() {
			pm_objDR["MA_THI_SINH"] = System.Convert.DBNull;
		}

		public string strHO_TEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "HO_TEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["HO_TEN"] = value;
			}
		}

		public bool IsHO_TENNull() 
		{
			return pm_objDR.IsNull("HO_TEN");
		}

		public void SetHO_TENNull() {
			pm_objDR["HO_TEN"] = System.Convert.DBNull;
		}

		public string strGIOI_TINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "GIOI_TINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["GIOI_TINH"] = value;
			}
		}

		public bool IsGIOI_TINHNull() 
		{
			return pm_objDR.IsNull("GIOI_TINH");
		}

		public void SetGIOI_TINHNull() {
			pm_objDR["GIOI_TINH"] = System.Convert.DBNull;
		}

		public string strNGAY_SINH 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["NGAY_SINH"] = value;
			}
		}

		public bool IsNGAY_SINHNull() 
		{
			return pm_objDR.IsNull("NGAY_SINH");
		}

		public void SetNGAY_SINHNull() {
			pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
		}

		public string strCMND 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "CMND", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["CMND"] = value;
			}
		}

		public bool IsCMNDNull() 
		{
			return pm_objDR.IsNull("CMND");
		}

		public void SetCMNDNull() {
			pm_objDR["CMND"] = System.Convert.DBNull;
		}

		public string strDIEN_THOAI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "DIEN_THOAI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["DIEN_THOAI"] = value;
			}
		}

		public bool IsDIEN_THOAINull() 
		{
			return pm_objDR.IsNull("DIEN_THOAI");
		}

		public void SetDIEN_THOAINull() {
			pm_objDR["DIEN_THOAI"] = System.Convert.DBNull;
		}

		public string strDIA_CHI 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "DIA_CHI", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["DIA_CHI"] = value;
			}
		}

		public bool IsDIA_CHINull() 
		{
			return pm_objDR.IsNull("DIA_CHI");
		}

		public void SetDIA_CHINull() {
			pm_objDR["DIA_CHI"] = System.Convert.DBNull;
		}

		public decimal dcID_DOI_TUONG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_DOI_TUONG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_DOI_TUONG"] = value;
			}
		}

		public bool IsID_DOI_TUONGNull()	{
			return pm_objDR.IsNull("ID_DOI_TUONG");
		}

		public void SetID_DOI_TUONGNull() {
			pm_objDR["ID_DOI_TUONG"] = System.Convert.DBNull;
		}

		public decimal dcID_KHU_VUC 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_KHU_VUC", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_KHU_VUC"] = value;
			}
		}

		public bool IsID_KHU_VUCNull()	{
			return pm_objDR.IsNull("ID_KHU_VUC");
		}

		public void SetID_KHU_VUCNull() {
			pm_objDR["ID_KHU_VUC"] = System.Convert.DBNull;
		}

		public string strUU_TIEN_YN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "UU_TIEN_YN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["UU_TIEN_YN"] = value;
			}
		}

		public bool IsUU_TIEN_YNNull() 
		{
			return pm_objDR.IsNull("UU_TIEN_YN");
		}

		public void SetUU_TIEN_YNNull() {
			pm_objDR["UU_TIEN_YN"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DS_HO_SO_THI_SINH() 
		{
			pm_objDS = new DS_DS_HO_SO_THI_SINH();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DS_HO_SO_THI_SINH(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DS_HO_SO_THI_SINH(decimal i_dbID) 
		{
			pm_objDS = new DS_DS_HO_SO_THI_SINH();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
