///************************************************
/// Generated by: tuandm
/// Date: 15/12/2015 10:52:10
/// Goal: Create User Service Class for DM_KHU_VUC
///************************************************
/// <summary>
/// Create User Service Class for DM_KHU_VUC
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DM_KHU_VUC : US_Object
	{
		private const string c_TableName = "DM_KHU_VUC";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public string strTEN_KHU_VUC 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TEN_KHU_VUC", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TEN_KHU_VUC"] = value;
			}
		}

		public bool IsTEN_KHU_VUCNull() 
		{
			return pm_objDR.IsNull("TEN_KHU_VUC");
		}

		public void SetTEN_KHU_VUCNull() {
			pm_objDR["TEN_KHU_VUC"] = System.Convert.DBNull;
		}

		public decimal dcDIEM_CONG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "DIEM_CONG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["DIEM_CONG"] = value;
			}
		}

		public bool IsDIEM_CONGNull()	{
			return pm_objDR.IsNull("DIEM_CONG");
		}

		public void SetDIEM_CONGNull() {
			pm_objDR["DIEM_CONG"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DM_KHU_VUC() 
		{
			pm_objDS = new DS_DM_KHU_VUC();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DM_KHU_VUC(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DM_KHU_VUC(decimal i_dbID) 
		{
			pm_objDS = new DS_DM_KHU_VUC();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
