///************************************************
/// Generated by: tuandm
/// Date: 15/12/2015 10:52:44
/// Goal: Create User Service Class for DS_NGUYEN_VONG
///************************************************
/// <summary>
/// Create User Service Class for DS_NGUYEN_VONG
/// </summary>

using System;
using IPCOREDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace IPCOREUS
{

	public class US_DS_NGUYEN_VONG : US_Object
	{
		private const string c_TableName = "DS_NGUYEN_VONG";
		#region Public Properties
		public decimal dcID 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID"] = value;
			}
		}

		public bool IsIDNull()	{
			return pm_objDR.IsNull("ID");
		}

		public void SetIDNull() {
			pm_objDR["ID"] = System.Convert.DBNull;
		}

		public decimal dcID_THI_SINH 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_THI_SINH", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_THI_SINH"] = value;
			}
		}

		public bool IsID_THI_SINHNull()	{
			return pm_objDR.IsNull("ID_THI_SINH");
		}

		public void SetID_THI_SINHNull() {
			pm_objDR["ID_THI_SINH"] = System.Convert.DBNull;
		}

		public decimal dcID_NGANH_TO_HOP_MON 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "ID_NGANH_TO_HOP_MON", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["ID_NGANH_TO_HOP_MON"] = value;
			}
		}

		public bool IsID_NGANH_TO_HOP_MONNull()	{
			return pm_objDR.IsNull("ID_NGANH_TO_HOP_MON");
		}

		public void SetID_NGANH_TO_HOP_MONNull() {
			pm_objDR["ID_NGANH_TO_HOP_MON"] = System.Convert.DBNull;
		}

		public decimal dcNGUYEN_VONG 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "NGUYEN_VONG", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["NGUYEN_VONG"] = value;
			}
		}

		public bool IsNGUYEN_VONGNull()	{
			return pm_objDR.IsNull("NGUYEN_VONG");
		}

		public void SetNGUYEN_VONGNull() {
			pm_objDR["NGUYEN_VONG"] = System.Convert.DBNull;
		}

		public decimal dcDIEM_XT 
		{
			get
			{
				return CNull.RowNVLDecimal(pm_objDR, "DIEM_XT", IPConstants.c_DefaultDecimal);
			}
			set	
			{
				pm_objDR["DIEM_XT"] = value;
			}
		}

		public bool IsDIEM_XTNull()	{
			return pm_objDR.IsNull("DIEM_XT");
		}

		public void SetDIEM_XTNull() {
			pm_objDR["DIEM_XT"] = System.Convert.DBNull;
		}

		public string strTRANG_THAI_TRUNG_TUYEN 
		{
			get 
			{
				return CNull.RowNVLString(pm_objDR, "TRANG_THAI_TRUNG_TUYEN", IPConstants.c_DefaultString);
			}
			set 
			{
				pm_objDR["TRANG_THAI_TRUNG_TUYEN"] = value;
			}
		}

		public bool IsTRANG_THAI_TRUNG_TUYENNull() 
		{
			return pm_objDR.IsNull("TRANG_THAI_TRUNG_TUYEN");
		}

		public void SetTRANG_THAI_TRUNG_TUYENNull() {
			pm_objDR["TRANG_THAI_TRUNG_TUYEN"] = System.Convert.DBNull;
		}

		#endregion


		#region Init Functions
		public US_DS_NGUYEN_VONG() 
		{
			pm_objDS = new DS_DS_NGUYEN_VONG();
			pm_strTableName = c_TableName;
			pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
		}

		public US_DS_NGUYEN_VONG(DataRow i_objDR): this()
		{
			this.DataRow2Me(i_objDR);
		}

		public US_DS_NGUYEN_VONG(decimal i_dbID) 
		{
			pm_objDS = new DS_DS_NGUYEN_VONG();
			pm_strTableName = c_TableName;
			IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
			v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
			SqlCommand v_cmdSQL;
			v_cmdSQL = v_objMkCmd.getSelectCmd();
			this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
			pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
		}
		#endregion


	}
}
